name: nasa_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  fluro: ^2.0.5
  dio: ^5.1.2
  logger: ^1.3.0
  built_value: ^8.5.0
  built_collection: ^5.1.1
  equatable: ^2.0.5
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  intl: ^0.18.1
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  video_player: ^2.6.1
  flutter_local_notifications: ^14.0.1
  path_provider: ^2.0.15
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  built_value_generator: ^8.5.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
